import React, { useState, useMemo } from 'react';
import { Play } from '../types';
import {
  PracticeDrill,
  getDrillsForPlay,
  DRILL_DATABASE,
} from '../data/drillDatabase';
import {
  Dumbbell,
  Target,
  Clock,
  CheckCircle2,
  AlertTriangle,
  Sparkles,
  Layers,
  Printer,
  Copy,
  Plus,
  Trash2,
  ChevronRight,
  ChevronDown,
  X,
  Play as PlayIcon,
  Pause,
  RotateCcw,
  Compass,
  FileText,
  Filter,
  Users,
  Shield,
  HelpCircle,
  Repeat,
  PlayCircle,
} from 'lucide-react';

interface DrillGeneratorModalProps {
  isOpen: boolean;
  onClose: () => void;
  currentPlay: Play;
  onPlayDrillOnField?: (
    drill: PracticeDrill,
    options?: { targetReps?: number; isAutoLoop?: boolean; initialSpeed?: number }
  ) => void;
}

export const DrillGeneratorModal: React.FC<DrillGeneratorModalProps> = ({
  isOpen,
  onClose,
  currentPlay,
  onPlayDrillOnField,
}) => {
  // Matched drills calculation based on current play
  const { primaryDrills, allMatchedDrills, analysis } = useMemo(() => {
    return getDrillsForPlay(currentPlay);
  }, [currentPlay]);

  // Selected drill for detailed drill card view
  const [selectedDrillId, setSelectedDrillId] = useState<string>(
    primaryDrills[0]?.id || DRILL_DATABASE[0].id
  );

  // Field playback configuration
  const [targetRepsSetting, setTargetRepsSetting] = useState<number>(6);
  const [autoLoopSetting, setAutoLoopSetting] = useState<boolean>(true);
  const [speedSetting, setSpeedSetting] = useState<number>(1.0);

  // Active filters
  const [categoryFilter, setCategoryFilter] = useState<string>('ALL');
  const [positionFilter, setPositionFilter] = useState<string>('ALL');
  const [difficultyFilter, setDifficultyFilter] = useState<string>('ALL');

  // Practice Script Builder state
  const [practicePlan, setPracticePlan] = useState<
    { drill: PracticeDrill; customMinutes: number; notes: string }[]
  >(() => [
    { drill: primaryDrills[0] || DRILL_DATABASE[0], customMinutes: 10, notes: 'Focus on sharp break angles' },
    { drill: primaryDrills[1] || DRILL_DATABASE[1], customMinutes: 10, notes: 'Full speed vs Cover 2 look' },
  ]);

  const [isScriptDrawerOpen, setIsScriptDrawerOpen] = useState(false);
  const [copySuccess, setCopySuccess] = useState(false);

  // Interactive Whistle / Period Timer state
  const [timerSeconds, setTimerSeconds] = useState(600); // 10 minutes default
  const [isTimerRunning, setIsTimerRunning] = useState(false);
  const [timerInitial, setTimerInitial] = useState(600);

  // Filtered drill list
  const filteredDrills = useMemo(() => {
    return allMatchedDrills.filter((d) => {
      if (categoryFilter !== 'ALL' && d.category !== categoryFilter) return false;
      if (
        positionFilter !== 'ALL' &&
        !d.targetPositions.includes(positionFilter as any)
      )
        return false;
      if (
        difficultyFilter !== 'ALL' &&
        d.difficulty !== difficultyFilter
      )
        return false;
      return true;
    });
  }, [allMatchedDrills, categoryFilter, positionFilter, difficultyFilter]);

  const activeDrill = useMemo(() => {
    return (
      DRILL_DATABASE.find((d) => d.id === selectedDrillId) ||
      filteredDrills[0] ||
      DRILL_DATABASE[0]
    );
  }, [selectedDrillId, filteredDrills]);

  // Add drill to practice plan
  const handleAddToPlan = (drill: PracticeDrill) => {
    if (practicePlan.some((item) => item.drill.id === drill.id)) return;
    setPracticePlan((prev) => [
      ...prev,
      { drill, customMinutes: drill.estimatedMinutes, notes: '' },
    ]);
  };

  const handleRemoveFromPlan = (drillId: string) => {
    setPracticePlan((prev) => prev.filter((item) => item.drill.id !== drillId));
  };

  const totalPlanMinutes = useMemo(() => {
    return practicePlan.reduce((sum, item) => sum + item.customMinutes, 0);
  }, [practicePlan]);

  // Copy Practice Script to Clipboard
  const handleCopyScript = () => {
    const textLines = [
      `🏈 PRACTICE SCRIPT: ${currentPlay.code} - ${currentPlay.englishName}`,
      `Total Duration: ${totalPlanMinutes} Minutes | Drills: ${practicePlan.length}`,
      `--------------------------------------------------`,
      ...practicePlan.map(
        (p, idx) =>
          `Period ${idx + 1} (${p.customMinutes} mins): ${p.drill.name}\n` +
          `  - Focus: ${p.drill.targetPositions.join(', ')} | ${p.drill.category}\n` +
          `  - Reps: ${p.drill.repCount}\n` +
          `  - Setup: ${p.drill.fieldSetup}\n` +
          `  - QB Key: ${p.drill.qbCoachingKey}\n` +
          `  - WR Key: ${p.drill.receiverCoachingKey}\n` +
          (p.notes ? `  - Coach Note: ${p.notes}\n` : '')
      ),
      `--------------------------------------------------`,
      `Generated by 8v8 Playbook Tactical Drill Generator (Finland University League)`,
    ];

    navigator.clipboard.writeText(textLines.join('\n')).then(() => {
      setCopySuccess(true);
      setTimeout(() => setCopySuccess(false), 2500);
    });
  };

  // Print Practice Script
  const handlePrintScript = () => {
    window.print();
  };

  // Timer Tick effect
  React.useEffect(() => {
    let interval: any = null;
    if (isTimerRunning && timerSeconds > 0) {
      interval = setInterval(() => {
        setTimerSeconds((prev) => {
          if (prev <= 1) {
            setIsTimerRunning(false);
            return 0;
          }
          return prev - 1;
        });
      }, 1000);
    }
    return () => {
      if (interval) clearInterval(interval);
    };
  }, [isTimerRunning, timerSeconds]);

  const formatTimer = (sec: number) => {
    const m = Math.floor(sec / 60);
    const s = sec % 60;
    return `${m.toString().padStart(2, '0')}:${s.toString().padStart(2, '0')}`;
  };

  if (!isOpen) return null;

  return (
    <div
      id="drill-generator-modal-backdrop"
      className="fixed inset-0 z-50 flex items-center justify-center p-2 sm:p-4 md:p-6 bg-slate-950/80 backdrop-blur-md overflow-hidden animate-in fade-in duration-200"
    >
      <div
        id="drill-generator-modal-container"
        className="relative w-full max-w-6xl h-[94vh] bg-slate-900 border border-slate-700/80 rounded-2xl sm:rounded-3xl shadow-2xl flex flex-col overflow-hidden text-slate-100"
      >
        {/* Modal Top Header */}
        <div className="px-5 py-4 bg-slate-850 border-b border-slate-700/80 flex flex-wrap items-center justify-between gap-3 shrink-0">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-2xl bg-amber-500/20 border border-amber-500/40 flex items-center justify-center text-amber-400 shadow-inner">
              <Dumbbell className="w-5 h-5" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h2 className="text-lg sm:text-xl font-black text-white tracking-tight font-display">
                  Tactical Drill Generator
                </h2>
                <span className="px-2 py-0.5 rounded-full text-[10px] font-mono font-bold bg-amber-400/10 text-amber-300 border border-amber-400/30">
                  Play-Matched
                </span>
              </div>
              <p className="text-xs text-slate-400">
                Translating{' '}
                <span className="font-mono font-bold text-amber-300">
                  {currentPlay.code}
                </span>{' '}
                into structured field practice periods
              </p>
            </div>
          </div>

          {/* Quick Action Buttons */}
          <div className="flex items-center gap-2">
            <button
              id="drill-script-builder-btn"
              onClick={() => setIsScriptDrawerOpen(!isScriptDrawerOpen)}
              className={`px-3 py-1.5 rounded-xl border text-xs font-bold flex items-center gap-1.5 transition-all shadow-sm ${
                isScriptDrawerOpen || practicePlan.length > 0
                  ? 'bg-amber-500 hover:bg-amber-600 text-slate-950 border-amber-400 shadow-amber-500/20'
                  : 'bg-slate-800 hover:bg-slate-700 text-slate-200 border-slate-700'
              }`}
            >
              <FileText className="w-3.5 h-3.5" />
              <span>Practice Script</span>
              <span className="px-1.5 py-0.2 rounded-full text-[10px] font-mono bg-slate-900 text-amber-300">
                {practicePlan.length}
              </span>
            </button>

            <button
              onClick={onClose}
              className="p-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-400 hover:text-white transition-colors"
              title="Close Modal"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Route Analysis Chip Banner */}
        <div className="px-5 py-2.5 bg-slate-800/80 border-b border-slate-700/60 flex flex-wrap items-center justify-between gap-3 text-xs">
          <div className="flex flex-wrap items-center gap-2">
            <span className="text-[11px] font-mono font-bold text-slate-400 uppercase tracking-wider flex items-center gap-1">
              <Sparkles className="w-3.5 h-3.5 text-amber-400" />
              Detected Routes &amp; Mechanics:
            </span>

            {analysis.routeCodes.map((code) => (
              <span
                key={`route-chip-${code}`}
                className="px-2 py-0.5 rounded-md text-[11px] font-mono font-bold bg-blue-500/20 text-blue-300 border border-blue-500/40"
              >
                Route #{code}
              </span>
            ))}

            {analysis.concepts.map((concept) => (
              <span
                key={`concept-chip-${concept}`}
                className="px-2 py-0.5 rounded-md text-[11px] font-mono font-bold bg-purple-500/20 text-purple-300 border border-purple-500/40"
              >
                {concept} Concept
              </span>
            ))}

            <span className="px-2 py-0.5 rounded-md text-[11px] font-mono bg-emerald-500/20 text-emerald-300 border border-emerald-500/40">
              Drop: {analysis.qbDrop}
            </span>
          </div>

          <div className="text-[11px] text-slate-400 font-mono">
            {primaryDrills.length} High-Priority Drills Matched
          </div>
        </div>

        {/* Modal Main Body: 2 Columns (Drill List / Filter on Left, Detailed Drill Card on Right) */}
        <div className="flex-1 flex flex-col md:flex-row overflow-hidden">
          {/* Left Column: Filter and Drill Selection List */}
          <div className="w-full md:w-80 lg:w-96 bg-slate-900/90 border-r border-slate-800 flex flex-col shrink-0 overflow-hidden">
            {/* Filter Bar */}
            <div className="p-3 border-b border-slate-800 space-y-2 bg-slate-850">
              <div className="flex items-center justify-between text-[11px] font-bold text-slate-400 uppercase tracking-wider">
                <span className="flex items-center gap-1">
                  <Filter className="w-3 h-3 text-amber-400" />
                  Filter Drills
                </span>
                <span className="text-slate-500 font-mono">
                  {filteredDrills.length} Drills
                </span>
              </div>

              <div className="grid grid-cols-2 gap-1.5">
                <select
                  value={categoryFilter}
                  onChange={(e) => setCategoryFilter(e.target.value)}
                  className="bg-slate-800 border border-slate-700 text-slate-200 text-xs rounded-lg px-2 py-1.5 focus:ring-1 focus:ring-amber-500 outline-none"
                >
                  <option value="ALL">All Categories</option>
                  <option value="ROUTE_PRECISION">Route Precision (Indy)</option>
                  <option value="COMBO_SKELETON">Combo Skeleton (Group)</option>
                  <option value="QB_MECHANICS">QB Footwork & Timing</option>
                  <option value="SCREEN_RUN">Screen & Perimeter</option>
                </select>

                <select
                  value={positionFilter}
                  onChange={(e) => setPositionFilter(e.target.value)}
                  className="bg-slate-800 border border-slate-700 text-slate-200 text-xs rounded-lg px-2 py-1.5 focus:ring-1 focus:ring-amber-500 outline-none"
                >
                  <option value="ALL">All Positions</option>
                  <option value="WR">WR (Wide Receiver)</option>
                  <option value="SLOT">Slot Receiver</option>
                  <option value="QB">Quarterback</option>
                  <option value="RB">Running Back</option>
                </select>
              </div>
            </div>

            {/* Drill Cards List */}
            <div className="flex-1 overflow-y-auto p-3 space-y-2.5">
              {filteredDrills.map((drill) => {
                const isSelected = drill.id === activeDrill.id;
                const isPrimary = primaryDrills.some((pd) => pd.id === drill.id);
                const isInPlan = practicePlan.some((item) => item.drill.id === drill.id);

                return (
                  <div
                    key={`drill-card-${drill.id}`}
                    onClick={() => setSelectedDrillId(drill.id)}
                    className={`p-3 rounded-2xl border transition-all cursor-pointer relative ${
                      isSelected
                        ? 'bg-amber-500/10 border-amber-500 shadow-md ring-1 ring-amber-500/30'
                        : 'bg-slate-850/90 border-slate-800 hover:border-slate-700 hover:bg-slate-800/80'
                    }`}
                  >
                    {isPrimary && (
                      <div className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[9px] font-mono font-bold bg-amber-400/20 text-amber-300 border border-amber-400/40 mb-1.5">
                        <Sparkles className="w-2.5 h-2.5" />
                        Top Play Recommendation
                      </div>
                    )}

                    <h3 className="text-xs font-bold text-white leading-snug">
                      {drill.name}
                    </h3>

                    <div className="flex flex-wrap items-center gap-2 mt-2 text-[11px] text-slate-400">
                      <span className="flex items-center gap-1 font-mono text-amber-400/90">
                        <Clock className="w-3 h-3" />
                        {drill.estimatedMinutes}m
                      </span>
                      <span>•</span>
                      <span className="font-mono text-slate-300">
                        {drill.targetPositions.join('/')}
                      </span>
                      <span>•</span>
                      <span className="text-[10px] px-1.5 py-0.5 rounded bg-slate-800 text-slate-300">
                        {drill.difficulty.split('/')[0]}
                      </span>
                    </div>

                    <div className="mt-2.5 pt-2 border-t border-slate-800 flex items-center justify-between text-[11px]">
                      <span className="text-[10px] text-slate-400 truncate max-w-[140px]">
                        {drill.targetRoutes.join(', ')}
                      </span>

                      <div className="flex items-center gap-1.5">
                        {onPlayDrillOnField && (
                          <button
                            onClick={(e) => {
                              e.stopPropagation();
                              onPlayDrillOnField(drill, {
                                targetReps: targetRepsSetting,
                                isAutoLoop: autoLoopSetting,
                                initialSpeed: speedSetting,
                              });
                            }}
                            title="Play drill on FieldBoard with auto-looping animation"
                            className="px-2 py-0.5 rounded-lg text-[10px] font-bold font-mono flex items-center gap-1 bg-emerald-600 hover:bg-emerald-500 text-white transition-all shadow-xs cursor-pointer"
                          >
                            <PlayIcon className="w-2.5 h-2.5 fill-white" />
                            <span>Play</span>
                          </button>
                        )}
                        <button
                          onClick={(e) => {
                            e.stopPropagation();
                            if (isInPlan) {
                              handleRemoveFromPlan(drill.id);
                            } else {
                              handleAddToPlan(drill);
                            }
                          }}
                          className={`px-2 py-0.5 rounded-lg text-[10px] font-bold font-mono flex items-center gap-1 transition-all ${
                            isInPlan
                              ? 'bg-emerald-500/20 text-emerald-300 border border-emerald-500/40'
                              : 'bg-slate-800 hover:bg-amber-500 hover:text-slate-950 text-slate-300 border border-slate-700'
                          }`}
                        >
                          {isInPlan ? (
                            <>
                              <CheckCircle2 className="w-3 h-3 text-emerald-400" />
                              <span>In Script</span>
                            </>
                          ) : (
                            <>
                              <Plus className="w-3 h-3" />
                              <span>+ Script</span>
                            </>
                          )}
                        </button>
                      </div>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>

          {/* Right Column: Full Detailed Drill Workbench & Diagram */}
          <div className="flex-1 bg-slate-950 p-4 sm:p-6 overflow-y-auto space-y-6">
            {/* Active Drill Title Bar & Plan Actions */}
            <div className="flex flex-col sm:flex-row sm:items-start justify-between gap-4 pb-4 border-b border-slate-800">
              <div className="space-y-1">
                <div className="flex flex-wrap items-center gap-2">
                  <span className="px-2.5 py-1 rounded-lg text-xs font-mono font-bold bg-amber-500/20 text-amber-300 border border-amber-500/30">
                    {activeDrill.category.replace('_', ' ')}
                  </span>
                  <span className="px-2.5 py-1 rounded-lg text-xs font-mono bg-slate-800 text-slate-300 border border-slate-700">
                    {activeDrill.difficulty}
                  </span>
                  <span className="px-2.5 py-1 rounded-lg text-xs font-mono text-emerald-400 bg-emerald-500/10 border border-emerald-500/20 flex items-center gap-1">
                    <Clock className="w-3.5 h-3.5" />
                    {activeDrill.estimatedMinutes} Mins
                  </span>
                </div>

                <h1 className="text-xl sm:text-2xl font-black text-white tracking-tight mt-1">
                  {activeDrill.name}
                </h1>
                <p className="text-xs text-slate-400 font-mono">
                  Targeted Positions:{' '}
                  <span className="text-slate-200 font-bold">
                    {activeDrill.targetPositions.join(', ')}
                  </span>{' '}
                  | Reps:{' '}
                  <span className="text-slate-200 font-bold">
                    {activeDrill.repCount}
                  </span>
                </p>
              </div>

              {/* Add to Script & Period Whistle Timer Controls */}
              <div className="flex flex-wrap items-center gap-2 shrink-0">
                {/* Rep / Whistle Timer */}
                <div className="flex items-center gap-2 px-3 py-1.5 rounded-xl bg-slate-900 border border-slate-800">
                  <div className="text-xs font-mono font-bold text-amber-400">
                    {formatTimer(timerSeconds)}
                  </div>
                  <button
                    onClick={() => setIsTimerRunning(!isTimerRunning)}
                    className="p-1 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-200"
                    title={isTimerRunning ? 'Pause Timer' : 'Start Period Timer'}
                  >
                    {isTimerRunning ? (
                      <Pause className="w-3.5 h-3.5 text-amber-400" />
                    ) : (
                      <PlayIcon className="w-3.5 h-3.5 text-emerald-400" />
                    )}
                  </button>
                  <button
                    onClick={() => {
                      setIsTimerRunning(false);
                      setTimerSeconds(activeDrill.estimatedMinutes * 60);
                    }}
                    className="p-1 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-400 hover:text-slate-200"
                    title="Reset to Drill Duration"
                  >
                    <RotateCcw className="w-3 h-3" />
                  </button>
                </div>

                <button
                  id="add-drill-to-plan-btn"
                  onClick={() => {
                    if (
                      practicePlan.some(
                        (item) => item.drill.id === activeDrill.id
                      )
                    ) {
                      handleRemoveFromPlan(activeDrill.id);
                    } else {
                      handleAddToPlan(activeDrill);
                    }
                  }}
                  className={`px-4 py-2 rounded-xl text-xs font-bold flex items-center gap-2 transition-all shadow-md active:scale-95 ${
                    practicePlan.some(
                      (item) => item.drill.id === activeDrill.id
                    )
                      ? 'bg-emerald-600 hover:bg-emerald-700 text-white shadow-emerald-600/30'
                      : 'bg-amber-500 hover:bg-amber-400 text-slate-950 shadow-amber-500/20'
                  }`}
                >
                  {practicePlan.some(
                    (item) => item.drill.id === activeDrill.id
                  ) ? (
                    <>
                      <CheckCircle2 className="w-4 h-4" />
                      <span>In Practice Script</span>
                    </>
                  ) : (
                    <>
                      <Plus className="w-4 h-4" />
                      <span>Add to Practice Script</span>
                    </>
                  )}
                </button>
              </div>
            </div>

            {/* Live FieldBoard Auto-Loop Playback Launchpad */}
            <div className="bg-gradient-to-r from-emerald-950/60 via-slate-900 to-slate-900 border-2 border-emerald-500/60 rounded-2xl p-4 shadow-lg flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
              <div className="space-y-1.5 flex-1">
                <div className="flex items-center gap-2">
                  <span className="px-2 py-0.5 rounded-full text-[10px] font-mono font-bold bg-emerald-500/20 text-emerald-300 border border-emerald-500/40 flex items-center gap-1">
                    <Repeat className="w-3 h-3 text-emerald-400" />
                    LIVE FIELDBOARD PLAYBACK
                  </span>
                  <span className="text-xs font-mono text-slate-400 font-bold">Auto-Loop Reps</span>
                </div>
                <p className="text-xs text-slate-300">
                  Execute this drill live on the tactical FieldBoard with agility cones, snap timing, and auto-looping reps.
                </p>
                <div className="flex flex-wrap items-center gap-3 pt-1 text-[11px] font-mono text-slate-300">
                  {/* Target Reps Selector */}
                  <div className="flex items-center gap-1.5">
                    <span className="text-slate-400">Reps:</span>
                    {[6, 8, 10, 0].map((reps) => (
                      <button
                        key={`reps-opt-${reps}`}
                        onClick={() => setTargetRepsSetting(reps)}
                        className={`px-2 py-0.5 rounded-md text-[10px] font-bold transition-all cursor-pointer ${
                          targetRepsSetting === reps
                            ? 'bg-emerald-500 text-slate-950 font-black'
                            : 'bg-slate-800 text-slate-300 hover:bg-slate-700'
                        }`}
                      >
                        {reps === 0 ? '∞' : reps}
                      </button>
                    ))}
                  </div>

                  {/* Auto-Loop Toggle */}
                  <label className="flex items-center gap-1.5 cursor-pointer select-none">
                    <input
                      type="checkbox"
                      checked={autoLoopSetting}
                      onChange={(e) => setAutoLoopSetting(e.target.checked)}
                      className="rounded text-emerald-500 focus:ring-0 focus:ring-offset-0 bg-slate-800 border-slate-700 w-3.5 h-3.5 cursor-pointer"
                    />
                    <span className="text-slate-300">Auto-Loop</span>
                  </label>

                  {/* Speed Setting */}
                  <div className="flex items-center gap-1.5">
                    <span className="text-slate-400">Speed:</span>
                    {[0.75, 1.0, 1.25].map((spd) => (
                      <button
                        key={`spd-opt-${spd}`}
                        onClick={() => setSpeedSetting(spd)}
                        className={`px-2 py-0.5 rounded-md text-[10px] font-bold transition-all cursor-pointer ${
                          speedSetting === spd
                            ? 'bg-amber-500 text-slate-950 font-black'
                            : 'bg-slate-800 text-slate-300 hover:bg-slate-700'
                        }`}
                      >
                        {spd}x
                      </button>
                    ))}
                  </div>
                </div>
              </div>

              {/* Big CTA Button */}
              {onPlayDrillOnField && (
                <button
                  id="launch-drill-fieldboard-cta"
                  onClick={() => {
                    onPlayDrillOnField(activeDrill, {
                      targetReps: targetRepsSetting,
                      isAutoLoop: autoLoopSetting,
                      initialSpeed: speedSetting,
                    });
                  }}
                  className="w-full sm:w-auto px-5 py-3 rounded-xl font-black text-xs uppercase tracking-wider flex items-center justify-center gap-2 bg-emerald-500 hover:bg-emerald-400 text-slate-950 shadow-lg shadow-emerald-500/25 active:scale-95 transition-all cursor-pointer shrink-0 border border-emerald-300/40"
                >
                  <PlayCircle className="w-4 h-4 fill-slate-950 text-emerald-400" />
                  <span>Play Drill on FieldBoard</span>
                </button>
              )}
            </div>

            {/* Tactical Drill Field Diagram (Schematic Layout) */}
            <div className="bg-slate-900 border border-slate-800 rounded-2xl p-4 overflow-hidden">
              <div className="flex items-center justify-between text-xs font-bold text-slate-400 uppercase tracking-wider mb-3">
                <span className="flex items-center gap-1.5 text-amber-400 font-mono">
                  <Compass className="w-4 h-4" />
                  Field &amp; Cone Alignment Diagram
                </span>
                <span className="text-[11px] font-mono text-slate-500">
                  Line of Scrimmage at 65%
                </span>
              </div>

              {/* Visual SVG Cone Grid Representation */}
              <div className="relative w-full h-52 sm:h-64 bg-slate-950 border border-slate-800 rounded-xl overflow-hidden shadow-inner flex items-center justify-center">
                <svg
                  className="w-full h-full"
                  viewBox="0 0 600 260"
                  preserveAspectRatio="xMidYMid meet"
                >
                  {/* Field Background Lines */}
                  <rect width="600" height="260" fill="#090d16" />

                  {/* Yardlines */}
                  <line
                    x1="0"
                    y1="50"
                    x2="600"
                    y2="50"
                    stroke="#1e293b"
                    strokeWidth="1.5"
                    strokeDasharray="4,4"
                  />
                  <text
                    x="20"
                    y="45"
                    fill="#475569"
                    fontSize="10"
                    fontFamily="monospace"
                  >
                    15 YARDS
                  </text>

                  <line
                    x1="0"
                    y1="110"
                    x2="600"
                    y2="110"
                    stroke="#1e293b"
                    strokeWidth="1.5"
                    strokeDasharray="4,4"
                  />
                  <text
                    x="20"
                    y="105"
                    fill="#475569"
                    fontSize="10"
                    fontFamily="monospace"
                  >
                    10 YARDS
                  </text>

                  <line
                    x1="0"
                    y1="160"
                    x2="600"
                    y2="160"
                    stroke="#1e293b"
                    strokeWidth="1.5"
                    strokeDasharray="4,4"
                  />
                  <text
                    x="20"
                    y="155"
                    fill="#475569"
                    fontSize="10"
                    fontFamily="monospace"
                  >
                    5 YARDS
                  </text>

                  {/* Line of Scrimmage (Blue) */}
                  <line
                    x1="0"
                    y1="200"
                    x2="600"
                    y2="200"
                    stroke="#3b82f6"
                    strokeWidth="2.5"
                  />
                  <text
                    x="20"
                    y="195"
                    fill="#60a5fa"
                    fontSize="11"
                    fontFamily="monospace"
                    fontWeight="bold"
                  >
                    LOS (Line of Scrimmage)
                  </text>

                  {/* QB Drop Line & Position */}
                  <circle cx="300" cy="240" r="10" fill="#3b82f6" />
                  <text
                    x="300"
                    y="244"
                    fill="#ffffff"
                    fontSize="10"
                    fontWeight="bold"
                    textAnchor="middle"
                  >
                    QB
                  </text>

                  {/* Pass trajectory arrow from QB to Target */}
                  <path
                    d="M 300 230 Q 340 160 380 95"
                    stroke="#f59e0b"
                    strokeWidth="2"
                    strokeDasharray="4,4"
                    fill="none"
                  />
                  <polygon points="380,90 373,98 385,98" fill="#f59e0b" />

                  {/* Cones & Route Stems based on diagramType */}
                  {activeDrill.diagramType === 'single-route' && (
                    <g>
                      {/* WR Stance on LOS */}
                      <circle cx="200" cy="200" r="9" fill="#10b981" />
                      <text
                        x="200"
                        y="204"
                        fill="#ffffff"
                        fontSize="9"
                        fontWeight="bold"
                        textAnchor="middle"
                      >
                        WR
                      </text>

                      {/* Stem Cone */}
                      <polygon
                        points="200,120 194,132 206,132"
                        fill="#f97316"
                      />
                      <text
                        x="215"
                        y="128"
                        fill="#fb923c"
                        fontSize="10"
                        fontFamily="monospace"
                      >
                        Break Cone
                      </text>

                      {/* Route Path */}
                      <path
                        d="M 200 190 L 200 125 L 380 90"
                        stroke="#10b981"
                        strokeWidth="3"
                        fill="none"
                      />
                      <polygon points="385,89 375,85 378,95" fill="#10b981" />

                      {/* Catch Point Target */}
                      <circle
                        cx="380"
                        cy="90"
                        r="12"
                        fill="none"
                        stroke="#eab308"
                        strokeWidth="2"
                        strokeDasharray="2,2"
                      />
                      <text
                        x="380"
                        y="94"
                        fill="#eab308"
                        fontSize="9"
                        fontFamily="monospace"
                        fontWeight="bold"
                        textAnchor="middle"
                      >
                        CATCH
                      </text>
                    </g>
                  )}

                  {activeDrill.diagramType === 'hi-lo-combo' && (
                    <g>
                      {/* Outside WR */}
                      <circle cx="160" cy="200" r="9" fill="#10b981" />
                      <text
                        x="160"
                        y="204"
                        fill="#ffffff"
                        fontSize="9"
                        fontWeight="bold"
                        textAnchor="middle"
                      >
                        #1
                      </text>
                      {/* Hitch Route Underneath */}
                      <path
                        d="M 160 190 L 160 155 L 155 160"
                        stroke="#06b6d4"
                        strokeWidth="3"
                        fill="none"
                      />
                      <polygon points="152,165 158,158 152,154" fill="#06b6d4" />
                      <text
                        x="110"
                        y="158"
                        fill="#22d3ee"
                        fontSize="9"
                        fontFamily="monospace"
                      >
                        Hitch (Low)
                      </text>

                      {/* Slot WR */}
                      <circle cx="240" cy="200" r="9" fill="#a855f7" />
                      <text
                        x="240"
                        y="204"
                        fill="#ffffff"
                        fontSize="9"
                        fontWeight="bold"
                        textAnchor="middle"
                      >
                        #2
                      </text>
                      {/* Corner Route High */}
                      <path
                        d="M 240 190 L 240 110 L 120 40"
                        stroke="#a855f7"
                        strokeWidth="3"
                        fill="none"
                      />
                      <polygon points="115,38 126,42 120,50" fill="#a855f7" />
                      <text
                        x="130"
                        y="35"
                        fill="#c084fc"
                        fontSize="9"
                        fontFamily="monospace"
                      >
                        Corner (High)
                      </text>

                      {/* Conflict Defender (Cornerback) */}
                      <polygon points="155,120 165,110 175,120 165,130" fill="#ef4444" />
                      <text
                        x="185"
                        y="123"
                        fill="#f87171"
                        fontSize="10"
                        fontFamily="monospace"
                        fontWeight="bold"
                      >
                        CB Dilemma
                      </text>
                    </g>
                  )}

                  {activeDrill.diagramType === 'mesh-cross' && (
                    <g>
                      {/* Left Slot Crosser */}
                      <circle cx="180" cy="200" r="9" fill="#10b981" />
                      <text
                        x="180"
                        y="204"
                        fill="#ffffff"
                        fontSize="9"
                        fontWeight="bold"
                        textAnchor="middle"
                      >
                        SL
                      </text>
                      <path
                        d="M 180 190 L 220 160 L 420 160"
                        stroke="#10b981"
                        strokeWidth="3"
                        fill="none"
                      />

                      {/* Right Slot Crosser */}
                      <circle cx="420" cy="200" r="9" fill="#a855f7" />
                      <text
                        x="420"
                        y="204"
                        fill="#ffffff"
                        fontSize="9"
                        fontWeight="bold"
                        textAnchor="middle"
                      >
                        SR
                      </text>
                      <path
                        d="M 420 190 L 380 156 L 180 156"
                        stroke="#a855f7"
                        strokeWidth="3"
                        fill="none"
                      />

                      {/* Mesh Rub Zone */}
                      <circle
                        cx="300"
                        cy="158"
                        r="14"
                        fill="#f59e0b"
                        fillOpacity="0.2"
                        stroke="#f59e0b"
                        strokeDasharray="2,2"
                      />
                      <text
                        x="300"
                        y="140"
                        fill="#fbbf24"
                        fontSize="10"
                        fontFamily="monospace"
                        fontWeight="bold"
                        textAnchor="middle"
                      >
                        6-INCH RUB ZONE
                      </text>
                    </g>
                  )}

                  {(activeDrill.diagramType === 'screen-train' ||
                    activeDrill.diagramType === 'rpo-box' ||
                    activeDrill.diagramType === 'qb-drop') && (
                    <g>
                      {/* Generic tactical alignment */}
                      <circle cx="220" cy="200" r="9" fill="#10b981" />
                      <circle cx="380" cy="200" r="9" fill="#06b6d4" />
                      <path
                        d="M 220 190 Q 250 140 320 80"
                        stroke="#10b981"
                        strokeWidth="3"
                        fill="none"
                      />
                      <polygon points="320,76 313,85 323,87" fill="#10b981" />
                      <polygon points="300,120 294,132 306,132" fill="#f97316" />
                    </g>
                  )}
                </svg>
              </div>

              {/* Equipment & Cone Setup details */}
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 mt-3 pt-3 border-t border-slate-800 text-xs">
                <div>
                  <span className="font-bold text-slate-400 font-mono text-[11px] uppercase">
                    Field Cone Setup:
                  </span>
                  <p className="text-slate-300 mt-0.5 leading-relaxed font-sans text-xs">
                    {activeDrill.fieldSetup}
                  </p>
                </div>
                <div>
                  <span className="font-bold text-slate-400 font-mono text-[11px] uppercase">
                    Equipment Needed:
                  </span>
                  <div className="flex flex-wrap gap-1.5 mt-1">
                    {activeDrill.equipment.map((eq, i) => (
                      <span
                        key={`eq-${i}`}
                        className="px-2 py-0.5 rounded bg-slate-800 text-slate-300 text-[11px] border border-slate-700"
                      >
                        {eq}
                      </span>
                    ))}
                  </div>
                </div>
              </div>
            </div>

            {/* Drill Step-by-Step Repetition Protocol */}
            <div className="bg-slate-900 border border-slate-800 rounded-2xl p-5 space-y-3">
              <div className="flex items-center gap-2 text-xs font-bold text-amber-400 uppercase tracking-wider">
                <Target className="w-4 h-4" />
                <span>Step-by-Step Drill Execution</span>
              </div>

              <div className="space-y-2.5">
                {activeDrill.stepByStep.map((step, idx) => (
                  <div
                    key={`step-${idx}`}
                    className="flex items-start gap-3 p-3 rounded-xl bg-slate-950/80 border border-slate-850"
                  >
                    <div className="w-6 h-6 rounded-lg bg-amber-500/20 border border-amber-500/40 text-amber-400 font-mono font-bold text-xs flex items-center justify-center shrink-0">
                      {idx + 1}
                    </div>
                    <p className="text-xs text-slate-200 leading-relaxed font-sans pt-0.5">
                      {step}
                    </p>
                  </div>
                ))}
              </div>
            </div>

            {/* Coaching Keys & Common Mistakes */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {/* Coaching Keys */}
              <div className="bg-slate-900 border border-slate-800 rounded-2xl p-5 space-y-3">
                <div className="flex items-center gap-2 text-xs font-bold text-emerald-400 uppercase tracking-wider">
                  <CheckCircle2 className="w-4 h-4" />
                  <span>Key Coaching Points</span>
                </div>

                <div className="space-y-3 text-xs">
                  <div className="p-3 rounded-xl bg-emerald-950/30 border border-emerald-800/40">
                    <span className="font-bold text-emerald-300 font-mono block mb-1">
                      QB Mechanics &amp; Timing:
                    </span>
                    <p className="text-slate-300 leading-relaxed">
                      {activeDrill.qbCoachingKey}
                    </p>
                  </div>

                  <div className="p-3 rounded-xl bg-blue-950/30 border border-blue-800/40">
                    <span className="font-bold text-blue-300 font-mono block mb-1">
                      Receiver Stride &amp; Break:
                    </span>
                    <p className="text-slate-300 leading-relaxed">
                      {activeDrill.receiverCoachingKey}
                    </p>
                  </div>
                </div>
              </div>

              {/* Common Mistakes to Correct */}
              <div className="bg-slate-900 border border-slate-800 rounded-2xl p-5 space-y-3">
                <div className="flex items-center gap-2 text-xs font-bold text-red-400 uppercase tracking-wider">
                  <AlertTriangle className="w-4 h-4" />
                  <span>Common Mistakes to Correct</span>
                </div>

                <div className="space-y-2">
                  {activeDrill.commonMistakes.map((mistake, i) => (
                    <div
                      key={`mistake-${i}`}
                      className="p-3 rounded-xl bg-red-950/20 border border-red-900/30 text-xs text-slate-300 flex items-start gap-2"
                    >
                      <span className="text-red-400 font-bold shrink-0">✕</span>
                      <span>{mistake}</span>
                    </div>
                  ))}
                </div>
              </div>
            </div>

            {/* Variations / Progression */}
            {activeDrill.variations && activeDrill.variations.length > 0 && (
              <div className="bg-slate-900/80 border border-slate-800 rounded-2xl p-4 flex items-center gap-3">
                <div className="p-2 rounded-xl bg-purple-500/20 border border-purple-500/30 text-purple-400 shrink-0">
                  <Sparkles className="w-4 h-4" />
                </div>
                <div className="text-xs">
                  <span className="font-bold text-purple-300 uppercase tracking-wider block font-mono text-[11px]">
                    Competitive Progression Variation:
                  </span>
                  <p className="text-slate-300 mt-0.5">
                    {activeDrill.variations.join(' • ')}
                  </p>
                </div>
              </div>
            )}
          </div>
        </div>

        {/* Sliding Practice Script Builder Drawer */}
        {isScriptDrawerOpen && (
          <div
            id="practice-script-drawer"
            className="absolute right-0 top-0 bottom-0 w-full sm:w-[420px] bg-slate-900 border-l border-slate-700 shadow-2xl z-40 flex flex-col animate-in slide-in-from-right duration-200"
          >
            <div className="p-4 bg-slate-850 border-b border-slate-700 flex items-center justify-between">
              <div className="flex items-center gap-2">
                <FileText className="w-4 h-4 text-amber-400" />
                <h3 className="text-sm font-bold text-white font-display">
                  Daily Practice Period Schedule
                </h3>
              </div>
              <button
                onClick={() => setIsScriptDrawerOpen(false)}
                className="p-1 rounded-lg hover:bg-slate-700 text-slate-400 hover:text-white"
              >
                <X className="w-4 h-4" />
              </button>
            </div>

            {/* Summary Metrics */}
            <div className="p-3 bg-slate-800/80 border-b border-slate-700/60 flex items-center justify-between text-xs font-mono">
              <div>
                <span className="text-slate-400">Total Period Time: </span>
                <span className="font-bold text-amber-400 text-sm">
                  {totalPlanMinutes} Mins
                </span>
              </div>
              <div>
                <span className="text-slate-400">Drills: </span>
                <span className="font-bold text-white">
                  {practicePlan.length}
                </span>
              </div>
            </div>

            {/* List of Scheduled Drills */}
            <div className="flex-1 overflow-y-auto p-4 space-y-3">
              {practicePlan.length === 0 ? (
                <div className="h-full flex flex-col items-center justify-center text-center p-6 text-slate-500 space-y-2">
                  <Dumbbell className="w-8 h-8 opacity-30 text-amber-400" />
                  <p className="text-xs">
                    No drills in your practice script yet. Click{' '}
                    <span className="text-amber-300 font-bold">+ Script</span> on
                    any drill card to build your practice plan!
                  </p>
                </div>
              ) : (
                practicePlan.map((item, idx) => (
                  <div
                    key={`plan-item-${item.drill.id}`}
                    className="p-3 rounded-xl bg-slate-950 border border-slate-800 space-y-2 relative"
                  >
                    <div className="flex items-center justify-between">
                      <span className="px-2 py-0.5 rounded-md text-[10px] font-mono font-bold bg-amber-500/20 text-amber-300 border border-amber-500/30">
                        PERIOD {idx + 1}
                      </span>
                      <button
                        onClick={() => handleRemoveFromPlan(item.drill.id)}
                        className="text-slate-500 hover:text-red-400 transition-colors p-1"
                        title="Remove from Script"
                      >
                        <Trash2 className="w-3.5 h-3.5" />
                      </button>
                    </div>

                    <h4 className="text-xs font-bold text-white leading-snug">
                      {item.drill.name}
                    </h4>

                    <div className="flex items-center justify-between pt-2 border-t border-slate-850 text-xs">
                      <div className="flex items-center gap-1.5">
                        <Clock className="w-3.5 h-3.5 text-slate-400" />
                        <input
                          type="number"
                          min={1}
                          max={60}
                          value={item.customMinutes}
                          onChange={(e) => {
                            const val = Math.max(1, parseInt(e.target.value) || 5);
                            setPracticePlan((prev) =>
                              prev.map((p) =>
                                p.drill.id === item.drill.id
                                  ? { ...p, customMinutes: val }
                                  : p
                              )
                            );
                          }}
                          className="w-12 px-1.5 py-0.5 bg-slate-850 border border-slate-700 rounded text-center text-xs font-mono font-bold text-amber-300 outline-none"
                        />
                        <span className="text-[11px] text-slate-400 font-mono">
                          Mins
                        </span>
                      </div>

                      <span className="text-[10px] font-mono text-slate-400">
                        {item.drill.targetPositions.join('/')}
                      </span>
                    </div>
                  </div>
                ))
              )}
            </div>

            {/* Script Footer Actions */}
            <div className="p-4 bg-slate-850 border-t border-slate-700 flex items-center gap-2">
              <button
                onClick={handleCopyScript}
                disabled={practicePlan.length === 0}
                className="flex-1 py-2.5 px-3 rounded-xl bg-amber-500 hover:bg-amber-400 disabled:opacity-50 text-slate-950 font-bold text-xs flex items-center justify-center gap-1.5 transition-all shadow-md active:scale-95"
              >
                {copySuccess ? (
                  <>
                    <CheckCircle2 className="w-4 h-4 text-slate-950" />
                    <span>Copied for Team Chat!</span>
                  </>
                ) : (
                  <>
                    <Copy className="w-4 h-4" />
                    <span>Copy Script</span>
                  </>
                )}
              </button>

              <button
                onClick={handlePrintScript}
                disabled={practicePlan.length === 0}
                className="py-2.5 px-3 rounded-xl bg-slate-800 hover:bg-slate-700 disabled:opacity-50 text-slate-200 border border-slate-700 text-xs font-bold flex items-center gap-1.5"
                title="Print Practice Cards"
              >
                <Printer className="w-4 h-4" />
                <span className="hidden sm:inline">Print</span>
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};
